### ISSUE TITLE
http: remote IP is never logged

### ISSUE THREAD

**Issue by jjakob** [cybozu-go/well#30]
https://github.com/cybozu-go/well/blob/2b248598cb276cf88cfb7137e982e164874f2740/http.go#L142-L145

Shouldn't this be if err == nil? Otherwise remote IP will never be logged.

**Comment by jjakob** [comment]
https://github.com/cybozu-go/well/pull/31

**Comment by ymmt2005** [comment]
Absolutely... Thank you!

**Comment by ymmt2005** [comment]
#31 was merged.  You are added to [AUTHORS](https://github.com/cybozu-go/well/commit/aeb2080eb80be3e842ac9db768cf19d949f7965c).
