### ISSUE TITLE
Does not cancel context on termination signal

### ISSUE THREAD

**Issue by Imunhatep** [cybozu-go/well#42]
here you go..  try to terminate this with ctrl+c

```go
package main

import (
	"context"
	"github.com/cybozu-go/well"
	"time"
)

func main() {
	env := well.NewEnvironment(context.Background())
	env.Go(func(ctx context.Context) error {
		for {
			select {
			case <-ctx.Done():
				return nil
			default:
			}
			time.Sleep(10 * time.Second)
		}
	})

	env.Stop()
	env.Wait()
}
```

**Comment by arosh** [comment]
@Imunhatep 
The SIGINT and SIGTERM handlers are not installed in the user-created Environments, whereas they are installed in the global Environment.

See [tutorial](https://github.com/cybozu-go/well/wiki/Tutorial#the-global-environment) and try the example below.

```go
package main

import (
        "context"
        "time"

        "github.com/cybozu-go/well"
)

func main() {
        well.Go(func(ctx context.Context) error {
                for {
                        select {
                        case <-ctx.Done():
                                return nil
                        default:
                        }
                        time.Sleep(10 * time.Second)
                }
        })

        well.Stop()
        well.Wait()
}
```

**Comment by Imunhatep** [comment]
Please improve docs, as that is not obvious, and even opposite to what is written and presented here: https://github.com/cybozu-go/well/wiki/Tutorial#context-and-environment

**Comment by zoetrope** [comment]
If you want `env` to respect parent context, you can pass parent context instead of `background.context`.

```go
package main

import (
	"context"
	"time"

	"github.com/cybozu-go/well"
)

func main() {

	well.Go(func(ctx context.Context) error {
		env := well.NewEnvironment(ctx)
		env.Go(func(ctx context.Context) error {
			for {
				select {
				case <-ctx.Done():
					return nil
				default:
				}
				time.Sleep(10 * time.Second)
			}
		})

		env.Stop()
		env.Wait()
		return nil
	})

	well.Stop()
	well.Wait()
}

**Comment by zoetrope** [comment]
I updated it.
https://github.com/cybozu-go/well/wiki/Tutorial#the-global-environment

**Comment by Imunhatep** [comment]
May be I'm not describing properly what I mean..
Documentation:  when docs are [opened](https://github.com/cybozu-go/well/wiki/Tutorial) and scrolled down to the topic **Context and Environment** it states right under it:  _Stop a goroutine on a signal or a deadline whichever comes first._  and right after it there is an example, that does fulfill the statement (Stop a goroutine on a signal) a few lines before.

The code: what I mean by propagating ctx by Environment, instead of presented example in docs, it would be, in my opinion, more proper to present this code, to demonstrate that **cancel** should be created and called manually:
```go
package main

import (
	"context"
	"fmt"
	"github.com/cybozu-go/well"
	"time"
)

func main() {
	cxl, cancel := context.WithCancel(context.Background())

	env := well.NewEnvironment(cxl)
	env.Go(func(ctx context.Context) error {
		fmt.Println("Running...")
		for {
			select {
			case <-ctx.Done():
				return nil
			default:
			}
			fmt.Println("Sleeping...")
			time.Sleep(10 * time.Second)
		}
	})

	go func() {
		defer cancel()
		time.Sleep(10 * time.Second)
		fmt.Println("cancelling...")
	}()

	env.Stop()
	env.Wait()
}
```
